### PR TITLE
better indentation with for expressions

### PR DESCRIPTION
**Pull request by wende**
screen shot 2016-08-08 at 15 51 06

Small fix to
#365

### CODE REVIEW

**Comment by wende** [comment]
Also I belive there's an error in tests:

https://github.com/elixir-lang/emacs-elixir/blob/master/test/elixir-mode-indentation-test.el#L1811

```
    for {k, v} <- keyword,
      v = process_value(v),
      into: %{}
      do: {v, k}
```

This code would generate a syntax error because of the lack of comma after `into: %{}` which also could (and probably should) lead to erroneous indentation

**Comment by wende** [comment]
Turns out it's still pretty bad if you've got more than `do:` in it

screen shot 2016-08-08 at 16 27 37

**Comment by whatyouhide** [comment]
Great job @wende. AFAIK, where `:into` should go has not been really discussed (at least not with me 😛) so not sure what the best behaviour would be here 😕 I'm gonna bring @lexmag into the conversation, wdyt Aleksei?

**Comment by lexmag** [comment]
I think it should be:
```
for {key, val} <- keyword,
  val = process_value(val),
  into: %{},
  do: {val, key}
```
i.e., same level as `do:`. :bowtie:

**Comment by wende** [comment]
But it looks weird with first line being indented differently then the others.
And it's already (kind of) working for `with` keyword

We've been discussing that in #371 

I'd say the biggest opinion based difference should be between
```
for {key, val} <- keyword,
    {key2, val2} <- keyword2,
    val = process_value(val),
    into: %{},
    do: {val, key}
```
and
```
for {key, val} <- keyword,
    {key2, val2} <- keyword2,
    val = process_value(val),
    into: %{},
  do: {val, key}
```
Or
```
for {key, val} <- keyword,
    {key2, val2} <- keyword2,
    val = process_value(val),
  into: %{},
  do: {val, key}
```

**Comment by whatyouhide** [comment]
I am against indenting the generators (`<-`) and filters (`=`) clauses one level more than the `for`, and I believe they should be indented 4 spaces (which mimics what we do with `with`):

```elixir
for x <- xs,
    y <- ys,
    x + y < z,
  do: x * y
```

**Comment by lexmag** [comment]
Sorry, my code snippet is incorrect, of course it should be 4 spaces (2 indentation levels).

**Comment by whatyouhide** [comment]
@lexmag ah, awesome, we agree on that then :) 👍

**Comment by whatyouhide** [comment]
Me and @lexmag revised the style guide for the [`for` special form](https://github.com/lexmag/elixir-style-guide#for-indentation) and the [`with` special form](https://github.com/lexmag/elixir-style-guide#with-indentation). What's the status on this PR?

**Comment by Trevoke** [comment]
How does this compare to the Elixir 1.6 formatter's decisions?

**Comment by whatyouhide** [comment]
@Trevoke it doesn't matter. Now that a formatter is there, I think that the editor should only be responsible for a basic indentation (like what we have today). Users that want everything as "standard" as possible will use the formatter. Uses that want to avoid the formatter and have custom styling and indentation rules will indent mostly by hand (as we couldn't support multiple rules in an editor anyways). My suggestion is to close this.

**Comment by jsmestad** [comment]
@axelson this can probably get closed out now that Elixir ships with the formatter.

**Comment by axelson** [comment]
Thanks, agreed. Maybe in the future when we have more spare time we could improve the formatting support further, but for now it makes sense to close it and focus elsewhere.

**Pull request closed without merging**
