### PR TITLE
Add error regexps for elixirc and credo

### PR DESCRIPTION
**Pull request by sirikid**

### CODE REVIEW

**Comment by sirikid** [comment]
1. The last few builds for Emacs 24.3 and 24.4 have failed, but are marked as successful.
2. Idk how to fix the issue with `alist-get` without `eval`, if no one has better suggestions I'll just publish this as a separate package for Emacs 25+.

**Comment by axelson** [comment]
@Trevoke any ideas on this?

**Comment by sirikid** [comment]
I am continuing to work on this [here](https://git.sr.ht/~sokolov/elixir-compile).

**Comment by sirikid** [comment]
All regexps are written using real build logs and re-builder.

**Pull request closed without merging**
