### PR TITLE
Add ~L, ~E, and ~e sigils for EEx and LiveView

### PR DESCRIPTION
**Pull request by jsmestad**
I think this is all that is needed.

Any idea how I could get highlighting to work inside the sigil by something like `web-mode` ?

### CODE REVIEW

**Comment by axelson** [comment]
Hmm, shouldn't we add support for `~E` as well? Unfortunately I'm not sure about how or if we could use `web-mode` to use HTML-based syntax within an Elixir file.

**Comment by jsmestad** [comment]
> Hmm, shouldn't we add support for `~E` as well? Unfortunately I'm not sure about how or if we could use `web-mode` to use HTML-based syntax within an Elixir file.

I wonder if we can look at what org-babel does to activate syntax highlighting on a particular region and see if we can duplicate that functionality?

**Comment by jsmestad** [comment]
Asking around I found out we can maybe use [polymode](https://github.com/polymode/polymode) for this.

I was also told that `org-babel` uses a separate buffer to render the block of code and then redirects the drawing to the main buffer. (TIL)

**Comment by jsmestad** [comment]
@axelson any chance we could get this merged in? I think it may also need a test?

**Comment by victorolinasc** [comment]
I am of the unpopular opinion that we shouldn't add anything related to Phoenix or Ecto or Absinthe or any other libraries. I understand this widely used but I don't think it belongs on this repo specifically.

I believe though that this is a common issue since JSX became more popular (just my opinion) that Emacs had to deal with many modes simultaneously. Also my opinion that polymode or other alternatives might be better here as pointed by @jsmestad .

As you've guessed, these are just opinions as I am not using these tools now. Fell free to totally ignore me here :)

**Comment by jsmestad** [comment]
@victorolinasc I hear what you are saying as it can be seen as bloat for those that do not make use of Phoenix and/or LiveView. However, the alternative of having distinct packages for `elixir-mode` and then some sort of `phoenix-mode` that extends it could be difficult to maintain given multiple major modes cannot really run together.

Is there an approach you've seen that would achieve a happy medium? I am no expert on Emacs major modes so I don't mean to "poke the bear" if I missed anything 🤲

**Comment by victorolinasc** [comment]
I think you are already much more enlightened than myself on the subject @jsmestad .

Polymode seems to me the way to go here. We can't have two major modes assigned to the same buffer (as far as I can tell...).

**Comment by axelson** [comment]
@jsmestad I'm still of the opinion that we should add `e` and `E` as well. A test would be great as (especially if a similar one already exists). Would polymode be something we add directly to emacs-elixir? Or would that be a solution that users need to add to their own configuration?

@victorolinasc I definitely hear what you're saying about not bloating emacs-elixir with phoenix/ecto/etc related code, but I'm not sure that's viable in practice since it would require a significant amount of work to maintain parallel major modes to support each of those.

@Trevoke any thoughts on this PR?

**Comment by jsmestad** [comment]
@axelson yeah we can add those as well.

I did have success getting polymode to work with LiveView templates. I put up [a blog post](https://blog.evalcode.com/phoenix-liveview-inline-syntax-highlighting-for-emacs/) with the code snippet to try it out. Could you give it a spin and see how if it works for you?

**Comment by axelson** [comment]
Oooh, I'll take a look at the blog post!

**Comment by jsmestad** [comment]
@axelson did you give it a try?

Also I think we can merge in this sigil thing as-is, no?

**Comment by jsmestad** [comment]
I looked through the test files and can confirm that not every sigil is tested, besides one set that was to protect against a bug reported in issue #23 

This should be good to merge. 👍

**Pull request merged**
