### PR TITLE
Elixir format when elixir installed with asdf

### PR DESCRIPTION
**Pull request by gabrielelana**
This PR will fix the broken build for all Elixir version with formatter (>= 1.6) and the issues related with asdf (#431 and #435)

[Open Source Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

### CODE REVIEW

**Comment by gabrielelana** [comment]
Closed and reopened the PR to rerun Travis tests :sweat_smile:

**Comment by vaer-k** [comment]
I'd really like to see this merged and released, but until then, is there a quick and dirty fix we can apply to effect these changes?

**Comment by vaer-k** [comment]
I just manually wrote these changes into my own copy of `elixir-format.el` for now.

**Comment by Trevoke** [comment]
Thank you!

**Pull request merged**
